name: GitHub_Actions_Pipeline_Workflows

on:
  push:
    branches:
      - gitapp
  pull_request:
    branches:
      - gitapp

jobs:
  Build:
    name: Azure Pipeline
    runs-on: ubuntu-latest
    steps:
    - name: Azure Pipelines Action
      uses: Azure/pipelines@v1
      with:
        azure-devops-project-url: https://dev.azure.com/Hexaware-Training/AgileProject
        azure-pipeline-name: "GitApp_Actions"
        azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
